### ISSUE TITLE
Losing exp when entering void world.

### ISSUE THREAD

**Issue by DarkestDreams24** [modmuss50/SimpleVoidWorld#10]
Everytime I use the portal no matter how much experience I have at the time it all goes to 0 whenever I reach the void world.

**Comment by modmuss50** [comment]
Can you go to the world, logout/close the world. And then login/open the world again? It might just be a syncing issue.

**Comment by DarkestDreams24** [comment]
Yep thats exactly what it is. Exp is restored on relog. Anyway to fix?

**Comment by modmuss50** [comment]
I will need to make sure the server sends the data to the client again when the dimension is changed

**Comment by DarkestDreams24** [comment]
Okay thankyou! Is there anything I can do on my end?

**Comment by modmuss50** [comment]
Sadly not, when you need to use your xp just re-log for now.

**Comment by DarkestDreams24** [comment]
Okay sorry haha. Feel free to close it when youre done xD

**Comment by modmuss50** [comment]
1.12 is no longer supported, sorry about this please update to the new 1.14.4 version. If the issue still happens there then open a new issue.

Thank you very much.
