### ISSUE TITLE
No need in RebornCore

### ISSUE THREAD

**Issue by exys228** [modmuss50/SimpleVoidWorld#11]
Why did you use RebornCore only for registering an one block and it's crafting recipe when you can just use GameRegistry? I don't want to add RebornCore in my mods folder only because of one portal block, and i had to remove RebornCore dependency from SimpleVoidWorld code by myself. By my opinion that's really absurd, small and simple mod shouldn't have any big and complicated dependencies.

**Comment by modmuss50** [comment]
If you dont want to use RC dont use the mod.
