### ISSUE TITLE
NightVision issue

### ISSUE THREAD

**Issue by Bass2style** [modmuss50/SimpleVoidWorld#13]
Hello,

when using Night Vision in the SimpleVoid world, everything is dark AF, i need to switch NightVision eveythime.

any workaround ? is this a normal "game aspect" or so ?

when Nightvision enabled : http://prntscr.com/fo0v60
when NightVision disabled : http://prntscr.com/fo0vo1

i use the Draconic evolution's armor Nightvision here, but a /effect nightvision gives same result.

**Comment by modmuss50** [comment]
In the config you should be able to disable night mode.

**Comment by Bass2style** [comment]
edited the config to disable the darkmode, and enabling "eternal day", and i always have the problem.

i'm running FTB Beyond 1.10.0 (pack version) that use 1.1.0.4 version of the mod.

**Comment by modmuss50** [comment]
1.12 is no longer supported, sorry about this please update to the new 1.14.4 version. If the issue still happens there then open a new issue.

Thank you very much.
