### ISSUE TITLE
Chunkloading/lighting/something doesn't work

### ISSUE THREAD

**Issue by TheUnderTaker11** [modmuss50/SimpleVoidWorld#14]
Mod version- Simple-Void-World-1.10.2-1.1.0.4-universal
Forge version 12.18.3.2281

The first buggy bit I encountered was when I tried to put a network receiver from RS in your dimension, and it simply didn't work. I thought, "Oh okay whatever probably a refined storage thing".    
But then I started setting up a farm with mystical agriculture and EnderIO, and it was very clear that the place either wasn't chunkloaded, or didn't think it was daytime while I was gone and woulden't grow crops. I had an imaginary time block placed so a steady flow of crops were feeding into the enderchest, yet it would get none while I was in a different dimension.    
Moving the setup to the end made it work perfectly. And yes, every step of this was all chunkloaded with chicken chunks.
Sorry I can't give any more specific details, but I do know the refined storage wiki said the receiver must be chunkloaded as well to work reliably, so that makes me think it never worked cause it wasn't chunkloaded properly.

**Comment by modmuss50** [comment]
1.12 is no longer supported, sorry about this please update to the new 1.14.4 version. If the issue still happens there then open a new issue.

Thank you very much.
