### ISSUE TITLE
[1.12] Cancel all right-click actions when using the portal

### ISSUE THREAD

**Issue by SnowShock35** [modmuss50/SimpleVoidWorld#15]
Hi @modmuss50,

I have a small request/bug for you regarding simple void would for Minecraft 1.12.

### Important Information

- Minecraft 1.12
- Minecraft Forge 14.21.1.2415
- SimpleVoidWorld 1.2.0.1

### Issue Details

When right clicking on the portal with any sort of item/block that has a right-click action, the game will attempt to perform this action while also activating the right-click action of the portal which ultimately teleports you to and from the void world.

**Comment by modmuss50** [comment]
This has been fixed in the 1.14.4 versions. I wont be going back to 1.12 now sorry.
