### ISSUE TITLE
Question: multi player shared

### ISSUE THREAD

**Issue by wizard1399** [modmuss50/SimpleVoidWorld#17]
Quick question. On multi player server is void world shared by all players? The reason I

**Comment by wizard1399** [comment]
am asking is that I want to pregenerate some structures in the void world for players to interact with. 

Also, do you always spawn in the same spot or is the spawn relative to where you placed the original portal block? Do not want players to port in only to find that the portal has messed up the structures I am going to create.

**Comment by wizard1399** [comment]
am asking is that I want to pregenerate some structures in the void world for players to interact with. 

Also, do you always spawn in the same spot or is the spawn relative to where you placed the original portal block? Do not want players to port in only to find that the portal has messed up the structures I am going to create.

**Comment by modmuss50** [comment]
There is only 1 void world and it is shared by all players. This helps keep the performance better. the portal is a 1:1 to where you placed it in the overworld. You can have more than one portal placed in different locations that go to different locations in the void world

**Comment by wizard1399** [comment]
Could you possible add a means of disabling portals around a certain point (0,0?) with a range that portals can not spawn in?
