### ISSUE TITLE
mcmod.info not in correct path

### ISSUE THREAD

**Issue by smbarbour** [modmuss50/SimpleVoidWorld#19]
mcmod.info should be in the root of the resources folder and not under `assets/<modid>/`

**Comment by thisischrys** [comment]
hmm weird I didn't touch any of that.
I'll have a look at it.

**Comment by modmuss50** [comment]
1.12 is no longer supported, sorry about this please update to the new 1.14.4 version. If the issue still happens there then open a new issue.

Thank you very much.

**Comment by smbarbour** [comment]
It's a moot point for 1.14.4 since mcmod.info isn't present in that version and the replacement has to be correct for Forge to load the mod and Fabric uses a different file as well.
