### ISSUE TITLE
Cannot create network link to Void World via Refined Storage.

### ISSUE THREAD

**Issue by Flapjacks** [modmuss50/SimpleVoidWorld#2]
I can create a network link to other dimensions (Aroma Mining World, Overworld) but when I try to link to a network receiver in SimpleVoidWorld, it doesn't seem to work.

Playing FTB Infinity Lite mudpack.

**Comment by Flapjacks** [comment]
Restarting the game fixes the network receiver.  If I break the link and remake it, it doesn't work again until another restart.

**Comment by modmuss50** [comment]
@<raoulvdberge> is an RS issue you can close
