### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by knoxhack** [modmuss50/SimpleVoidWorld#20]
Could you add a way to teleport players to the same dimension the void world block is located. For example If you place the void world block in The Aether dimension it takes you back to the same dimension when teleported back.

Playing on a modpack where the Overworld is locked out and it (portal void block) keeps teleporting players back to the Overworld when they coming back.

**Comment by modmuss50** [comment]
This is going to be hard to add, as I would need to keep track of where the player came from. For now I dont think this is worth the effort required to add it.

Thanks for the suggestion anyway.
