### ISSUE TITLE
[Fabric] Crash on load java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/itemgroup/FabricItemGroupBuilder

### ISSUE THREAD

**Issue by donqixot** [modmuss50/SimpleVoidWorld#23]
This is my first attempt to load Fabric client, so I am not sure what is going on. I followed instruction on loading Fabric client in MultiMC (http://fabric.asie.pl/use/), started instance, all good. Then I added SimpleVoidWorld-2.0.1 to the mods folder and tried again. Got crash
[crash-2018-12-30_22.57.56-client.txt](https://github.com/modmuss50/SimpleVoidWorld/files/2717730/crash-2018-12-30_22.57.56-client.txt)
I was using Fabric 18w50a.83-0.3.1.83, fabric-loader:0.3.1.83, I have MultiMC 5, version 0.6.3-1285. During installation I copied MultiMc instance url to clipboard and then pasted it in MultiMC when adding new instance, just as instructions suggested - http://fabric.asie.pl/wiki/install.

**Comment by modmuss50** [comment]
A lot of mods including this one also require Fabric(API) to be installed into the mods folder. 

https://minecraft.curseforge.com/projects/fabric

You have only installed fabric-loader.

**Comment by donqixot** [comment]
Thank you for quick response!
