### ISSUE TITLE
Astral sorcery Compat

### ISSUE THREAD

**Issue by majijn** [modmuss50/SimpleVoidWorld#24]
I was asking around in the AS discord, because while AS does recognise there's some starlight in the dimension, 
it's extremely weak, and several multiblocks dont work at all because they're not getting enough power
 and they asked if the dimension has a flowing time handler

**Comment by modmuss50** [comment]
1.12 is no longer supported, sorry about this please update to the new 1.14.4 version. If the issue still happens there then open a new issue.

Thank you very much.
