### ISSUE TITLE
Spawning is broken

### ISSUE THREAD

**Issue by ghost** [modmuss50/SimpleVoidWorld#26]
Forge: x.2824
SimpleVoidWorld: 1.2.0.9
Modpack: Continuity RC2B

This is two parts.

1- When I enter the void world I am not being put on my platform properly, and am being placed 8-10 blocks or so away from it, causing me to fall into the void. No, nothing is shooting me off, no mobs are present. It's likely an interaction between this and some other mod, as it doesn't happen with just this mod installed. I'll do further investigation later if needed.
Maybe it would be possible to implement a check to make sure there's a tangible block below the player before putting them there.

2-The default for the respawning should be to spawn back in the overworld, as it's very likely that the spawn location is not going to have anything there to catch the player (thusly if a player dies in the void world they have to start over unless they enabled cheats!)

**Comment by modmuss50** [comment]
1.12 is no longer supported, sorry about this please update to the new 1.14.4 version. If the issue still happens there then open a new issue.

Thank you very much.

**Comment by DemonfangArun** [comment]
1.12.2, while old, is still the go-to for pack makers, and will be for a while yet. You've told me what I needed to know and I will no longer be using your mods in the future.
