### ISSUE TITLE
Void world lag

### ISSUE THREAD

**Issue by ghost** [modmuss50/SimpleVoidWorld#27]
This is a problem i have with the void world when i enter from the mining dimension. (from aromas mining dimension mod). When i enter, the tick time (/forge tps) is very high, and stays that way. When i enter back into the mining dimension, everything is fine again. Also, when i enter back into the void world portal to get back to the mining world, it instead brings me to my overworld base.
I'm wondering if this is just my case.

Thanks.

**Comment by modmuss50** [comment]
1.12 is no longer supported, sorry about this please update to the new 1.14.4 version. If the issue still happens there then open a new issue.

Thank you very much.
