### ISSUE TITLE
Bug when using Map Writer

### ISSUE THREAD

**Issue by MrAmericanMike** [modmuss50/SimpleVoidWorld#3]
So, when using this mod with Map Writer 2, the map gets confuse and doesn't know what dimension to render.

I report it here, because I haven't seen Map Writer 2 do this with any other dimension from any mod.

I assume it doesn't know that the player was moved to Dim 43 as when you open the Map with M it still says Dim 0

Using:

Forge  12.18.3.2185
SimpleVoidWorlds 1.10.2 1.0.0.2
RebornCore 2.8.2.69
MapWriter 2 2.6.19 https://minecraft.curseforge.com/projects/mapwriter-2

**Comment by modmuss50** [comment]
Oh right, humm. I will need to look into this as I think I use the vanilla way to teleport players. I might have missed an event call or something.

**Comment by MrAmericanMike** [comment]
I'm familiar with modding, but not much when it comes to teleporting and stuff. Maybe taking a look here can help you ;)

https://github.com/kegare/Cavern/blob/master/cavern/block/BlockPortalCavern.java

**Comment by modmuss50** [comment]
Should be fixed in the new update.

**Comment by MrAmericanMike** [comment]
Thanks a lot, will update and take a look at how it behaves now ;)
