### ISSUE TITLE
need to label 1.14.4 fabric / forge for correctly label 

### ISSUE THREAD

**Issue by raziel23x** [modmuss50/SimpleVoidWorld#32]
for 1.14.4 you have not flagged this as fabric and this causes many issues with us who are making 1.14.x modpack and causes though of us using forge to download this thinking this is for forge instead of fabric please use the fabric tag to correctly label this on curse forge so though of us who does not use fabric does not waste our time downloading this

**Comment by modmuss50** [comment]
Will do for the next version, sorry.
