### ISSUE TITLE
Questions about modpack permissions and multiplayer functionality...

### ISSUE THREAD

**Issue by RubyRezal** [modmuss50/SimpleVoidWorld#33]
Hello,
I found SimpleVoidWorld on CurseForge but I have a couple of questions and didn't see any other way to ask them. I hope it is ok with you if I ask them here.

I'm looking to build a private multiplayer server and I would like to include SimpleVoidWorld mostly because I like Skyblock and my friends don't but I don't want to have to leave the server if I want to build in the sky for a while.  I'd like to make it easy for my friends to get all the mods so I'm working to build a private modpack to be hosted on CurseForge with possible easy distribution and installation through the FTB launcher.

Most of the mods I'm including give open permission to be included in modpacks as long as the modpack curator gives proper accreditation and isn't going to try to sell the modpack for financial gain.  I didn't see any modpack permissions on the SimpleVoidWorld page.
Would you be willing to grant such permission under the common terms?  I agree to give proper accreditation by listing all mods in my modpack by name, linking to their pages on CurseForge or another home site of the mod author's choice, and that distribution of the modpack will be free.

The second question I have is about multiplayer functionality: How does this mod work in a multiplayer environment?  What happens if multiple players craft and use the block that transports them to the void world?  My primary concern here is anti-griefing, if I include this mod on my server I don't want people showing up uninvited to my island in the void.

**Comment by modmuss50** [comment]
Feel free to use any of my mods in your mod pack.

This mod creates one world, and the portals are spawned at 1-1 with the overworld portal that you place.
