### ISSUE TITLE
[questions] about this mod

### ISSUE THREAD

**Issue by kreezxil** [modmuss50/SimpleVoidWorld#36]
1. Can it be set to be the default world for the overworld?
1. Can I change the makeup of the starting island in the void?
1. If on a server, does each player get their own spot in this void or their own void dim?
a. if own spot in the same dimension, can I change the padding between spots
1. Can disable the other dimensions?

**Comment by kreezxil** [comment]
@modmuss50

**Comment by modmuss50** [comment]
1) not currenly
2) not currenly, good idea tho
3) its just one world, the portals are located 1-1 with their overworld position
4) no

**Comment by kreezxil** [comment]
so to make a sky block pack in 1.14 that is smp, I would have to have another mod that did random overworld logins over a wide area, puts each player in a bottle and gives them a portal. Ironcally that sounds like StoneBlock dimensions which hasn't ported up yet.
