### ISSUE TITLE
[1.12-1.2.0.9] Teleported to a quasi inbetween dimension

### ISSUE THREAD

**Issue by itanshi** [modmuss50/SimpleVoidWorld#37]
oddly, this also happened with the deep dark portal

if its a desync, i can't log back in to finish the test. i think the server doesnt know where i am

https://cdn.discordapp.com/attachments/294303679262228480/666066410048454657/2020-01-12_17.48.36.png

**Comment by modmuss50** [comment]
1.12 version isnt supported, sorry. I dont think its my issue anyway.
