### ISSUE TITLE
Teleport Block acting weird

### ISSUE THREAD

**Issue by MrAmericanMike** [modmuss50/SimpleVoidWorld#4]
Well, in this case a video is better than explaining, but.... Take a look at what the block is doing:

https://clips.twitch.tv/jonbams/PoorWeaselArsonNoSexy

It moves by itself :S

**Comment by modmuss50** [comment]
Do you know if he is playing in single or multiplayer?

**Comment by MrAmericanMike** [comment]
Yes that happens on a Single Player World.

**Comment by DimkaAkuma** [comment]
when i place teleport block high above ground (platform high up in the air) i can sometimes see a block texture on the ground , like 100 coordinates lower. after some time the right texture for block is reapplied(dirt)
The thing is - in void word Teleportblock is in y=65 position, in Overworld its in y=150. So...  the Overworld block which is in y=65 pos, sometimes gets  a texture  of a TeleportBlock. Guess in that video its same thing - a block 1 coordinate higher gets a texture, cause  in VoidDimension (DIM43) theres a TelportBlock in that coordinates.

**Comment by modmuss50** [comment]
Yeah, thats not a bad idea.

**Comment by modmuss50** [comment]
1.12 is no longer supported, sorry about this please update to the new 1.14.4 version. If the issue still happens there then open a new issue.

Thank you very much.
