### ISSUE TITLE
Dont spawn mobs on VoidWorld

### ISSUE THREAD

**Issue by MATISAKU** [modmuss50/SimpleVoidWorld#5]
Like u can see on this video does not spawn mobs, can u help me?
Only spawn with a mobspawner, how can i change this? in config there is nothing!
Sorry my english.

Video of proof: https://youtu.be/qmfAH-eTAPQ

**Comment by modmuss50** [comment]
I should be able to add a config

**Comment by MATISAKU** [comment]
If u can do that will be awsome if u can let me know Thanks

**Comment by modmuss50** [comment]
Fixed
