### ISSUE TITLE
Can't Find Mod Options

### ISSUE THREAD

**Issue by Wh4tsMyName** [modmuss50/SimpleVoidWorld#6]
Oddly enough, I can't find the options for this mod. I don't think there's any conflicting mods, though I do use OptiFine -- which changes the visual settings screen.

**Comment by modmuss50** [comment]
in the config folder.

**Comment by Wh4tsMyName** [comment]
I know where that is, but I can't change the config options.

**Comment by modmuss50** [comment]
I'm not sure what you mean?

**Comment by Wh4tsMyName** [comment]
I'm opening the config file in Notepad++, but I can't change the options. Even when I open it in something else, like just plain old Notepad, they're unchangeable. [This](https://github.com/modmuss50/SimpleVoidWorld/blob/master/src/main/java/me/modmuss50/svw/Config.java) is the file I'm talking about. I see what I'm looking for, but on N++ it's just a "4."

**Comment by modmuss50** [comment]
Try deleting it and starting the game again to reload it

**Comment by Wh4tsMyName** [comment]
Still no options to be found...

**Comment by milkev** [comment]
the config file does not generate on fabric 1.16.4
running the latest applicable version of simple void world, fabric api, and fabric.
Nothing shows up in mod menu either, theres no links registered for the mod either.
Mod works as expected in world.
![image](https://user-images.githubusercontent.com/22010128/105472244-ed1e5e80-5c58-11eb-92ba-b5fb35c514b5.png)
