### ISSUE TITLE
Remove portal block?

### ISSUE THREAD

**Issue by InflamedSebi** [modmuss50/SimpleVoidWorld#7]
I moved my portal several times, so I created a few platforms in the void. Now try to remove the floating platforms in the void, but I can't break the Portal block .... Is there a way to remove those floating portal blocks?

**Comment by modmuss50** [comment]
No there isnt. It prevents people from duping them.

**Comment by InflamedSebi** [comment]
Hmm ... how about a tool to break it without loot? Or just make it drop no loot in general while in this dim?
