### ISSUE TITLE
Can't Keep World Loaded

### ISSUE THREAD

**Issue by xlxAciDxlx** [modmuss50/SimpleVoidWorld#8]
I don't know if this is some sort of fluke or if I need to do something else, but I cannot get the world/chunks to stay loaded using ChickenChunks on a server. The chunk loaders themselves seem to be working because everything in the Overworld is still working, but once I leave the void world I see "unloaded dimension 43" in the server console.

*ChickenChunks:* 2.2.0.52
*SimpleVoidWorld:* 1.1.0.4

**Comment by gigabit101** [comment]
I have had a few little issues with ChickenChunks and loading other dimensions so im not sure whos side this is on @covers1624 might no more

**Comment by xlxAciDxlx** [comment]
Hmm, that may be the case. I don't really have any other dimensions to try it on besides the Nether.

**Comment by gigabit101** [comment]
I was having issues keeping RFTools worlds loaded with it but no issues with the Extra Utils loader

**Comment by th4umiel** [comment]
Also Random Things' Ender Anchor works 👍
